import type { AssistedCurriculumDraft, AssistedDraftValidatorReport, CurriculumTargetRegistry } from "./contracts";
export type AssistedDraftRepositoryErrorCode = "ADR-001" | "ADR-002" | "ADR-003" | "ADR-004" | "ADR-005";
export interface AssistedDraftStableRecord { packageId: string; version: number; savedAt: string; draft: AssistedCurriculumDraft; validatorReport: AssistedDraftValidatorReport; }
export interface AssistedDraftRecoveryRecord { packageId: string; recoveryId: string; basedOnVersion: number; createdAt: string; draft: AssistedCurriculumDraft; validatorReport: AssistedDraftValidatorReport; }
export interface AssistedDraftCommitResult { committed: boolean; currentVersion: number; }
export interface AssistedDraftStorageAdapter { readStable(packageId: string): Promise<AssistedDraftStableRecord | null>; commitStable(record: AssistedDraftStableRecord, expectedVersion: number): Promise<AssistedDraftCommitResult>; readRecovery(packageId: string): Promise<AssistedDraftRecoveryRecord | null>; commitRecovery(record: AssistedDraftRecoveryRecord, expectedStableVersion: number): Promise<AssistedDraftCommitResult>; deleteRecovery(packageId: string): Promise<void>; }
export interface AssistedDraftRepository { load(packageId: string): Promise<AssistedDraftStableRecord | null>; save(draft: AssistedCurriculumDraft, options?: { expectedVersion?: number | null }): Promise<AssistedDraftStableRecord>; saveRecovery(draft: AssistedCurriculumDraft, options?: { expectedVersion?: number | null }): Promise<AssistedDraftRecoveryRecord>; getRecovery(packageId: string): Promise<AssistedDraftRecoveryRecord | null>; restoreRecovery(packageId: string, options?: { expectedVersion?: number | null }): Promise<AssistedDraftStableRecord>; discardRecovery(packageId: string): Promise<void>; }
export class AssistedDraftRepositoryError extends Error { code: AssistedDraftRepositoryErrorCode; details: Record<string, unknown>; }
export function createInMemoryDraftStorage(): AssistedDraftStorageAdapter & { simulateNextCommitFailure(): void };
export function createAssistedDraftRepository(options: { storage: AssistedDraftStorageAdapter; registry: CurriculumTargetRegistry; now?: () => string; }): AssistedDraftRepository;
